services:
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 <em># Poll every 60 seconds</em>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
  express-app:
    image: pacotacou/cash-register-go
    ports: 
      - 8080:8080
    container_name: cash-register-go